language: ruby
cache: bundler
branches:
  only:
  -  master
addons:
  ssh_known_hosts: git.wpengine.com
script:
- cd wp-content/themes/aerospace
- compass compile
before_install:
- openssl aes-256-cbc -K $encrypted_9c605297409a_key -iv $encrypted_9c605297409a_iv
  -in aerospace_travis.enc -out /tmp/aerospace_travis -d
- gem install compass
before_deploy:
- cd $TRAVIS_BUILD_DIR
deploy:
- provider: script
  skip_cleanup: true
  script: chmod +x deploy.sh && sh deploy.sh
  on:
    branch: master